name: 'HuskTowns'
description: '${description}'
author: 'William278'
website: 'https://william278.net/project/husktowns'
main: 'net.william278.husktowns.BukkitHuskTowns'
version: '${version}'
api-version: 1.16
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
softdepend:
  - 'Vault'
  - 'PlaceholderAPI'
  - 'dynmap'
  - 'BlueMap'
  - 'Pl3xMap'
  - 'LuckPerms'
  - 'HuskHomes'
  - 'Plan'
  - 'WorldGuard'