# Builds, tests the project with Gradle
name: CI Tests

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'workflows/**'
      - 'README.md'

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test publish
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v3
        if: success() || failure() 
        with:
          name: paper
          path: paper
          if-no-files-found: error  
