name: 'HuskTowns'
description: '${description}'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.husktowns.PaperHuskTowns'
loader: 'net.william278.husktowns.PaperHuskTownsLoader'
version: '${version}'
api-version: 1.19
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    RedisEconomy:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    dynmap:
      load: BEFORE
      required: false
    BlueMap:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    HuskHomes:
      load: BEFORE
      required: false
    Plan:
      load: BEFORE
      required: false